language: node_js
node_js:
  - "node"
  - "8"
addons:
  code_climate:
    repo_token: 033efc868120808faa564200fe1b302bac2059910ca4fcdaddbe8174179863f9
after_script:
  - npm run coverage
  - cat coverage/lcov.info | node_modules/.bin/codeclimate-test-reporter
